apiVersion: v1
kind: Service
metadata:
  name: '{{ env_prefix }}-{{ resource_name }}'
  namespace: '{{ env }}'
  labels:
    app: '{{ env_prefix }}-{{ resource_name }}'
spec:
  type: NodePort
  selector:
    app: '{{ env_prefix }}-{{ resource_name }}'
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
