---
# Hosts
all:
  hosts:
    # Localhost
    localhost:
      ansible_connection: local
      ansible_user: ansible
      ansible_host: 127.0.0.1

    # Local Minikube cluster
    minikube:
      ansible_connection: local
      ansible_user: minikube
      ansible_host: 192.168.56.100
    
    # Kubernetes Cluster -- Uncomment below lines to add a K8s host
    # k8sCluster:
    #   ansible_python_interpreter: /home/travis/virtualenv/python3.6.7/bin/python3
    #   ansible_connection: local
    #   ansible_user: ansible
    #   ansible_host: 192.168.56.100
...
